export let ADD_TODO = 'ADD_TODO';
export let FETCHING_ADD_TODO = 'FETCHING_ADD_TODO';
export let SUCCESS_ADD_TODO = 'SUCCESS_ADD_TODO';
export let FAILURE_ADD_TODO = 'FAILURE_ADD_TODO';

export let REMOVE_TODO = 'REMOVE_TODO';
export let FETCHING_REMOVE_TODO = 'FETCHING_REMOVE_TODO';
export let SUCCESS_REMOVE_TODO = 'SUCCESS_REMOVE_TODO';
export let FAILURE_REMOVE_TODO = 'FAILURE_REMOVE_TODO';

export let UPDATE_TODOS = 'UPDATE_TODOS';
export let FETCHING_TODOS = 'FETCHING_TODOS';
export let FAILURE_TODOS = 'FAILURE_TODOS';

export let UPDATE_FILTERED_TODOS = 'UPDATE_FILTERED_TODOS';
export let FETCHING_FILTERED_TODOS = 'FETCHING_FILTERED_TODOS';
export let SUCCESS_FILTERED_TODOS = 'SUCCESS_FILTERED_TODOS';
export let FAILURE_FILTERED_TODOS = 'FAILURE_FILTERED_TODOS';

export let UPDATE_SEARCH_MODE = 'UPDATE_SEARCH_MODE';
